### ISSUE TITLE
Redesign the UI

### ISSUE THREAD

**Issue by PooriaT** [PooriaT/Resumivise#67]

**Comment by alchuu00** [comment]
Hey Pooria, I'd like to redesign the UI. I have something like this in mind if that's okay with you.
![Screenshot_1](https://github.com/PooriaT/Resumivise/assets/112892699/e8fc50e7-903a-4e97-a190-c9bf854ce0eb)

**Comment by PooriaT** [comment]
Hi Alja,

Yeah, that's fine. Feel free to make the changes.

**Comment by alchuu00** [comment]
Great, I'll go ahead and start remaking the UI. And yes, I've got responsiveness covered :)

**Comment by PooriaT** [comment]
Done
